### ISSUE TITLE
API Completion Checklist

### ISSUE THREAD

**Issue by itsmemattchung** [wastatickets/softix#1]
This is the Dubai API Govt API Checklist:
## TODO
- [x] Generate Basket (section, "best available")
- [x] Basket Offers
- [x] Basket View
- [x] Basket Purchase
- [x] View Orders
## Not supported
- [ ] Generate Basket (seat)
- [x] Return Orders
- [ ] Basket Remove
- [ ] Basket with HOLDS
- [ ] All Calls - Load tested
- [ ] Terminology Mapping
## Done
- [x] Access Token
- [x] Performance Availibities
- [x] Customers 
- [x] Performance Prices

**Comment by itsmemattchung** [comment]
At the moment, softixcli supports adding customers, and retrieving performance data (availabilities and prices):

```bash
$ softix --help
Usage: softix [OPTIONS] COMMAND [ARGS]...

Options:
  --client-id TEXT    Client ID
  --secret TEXT       Secret
  --seller-code TEXT  Seller code
  --help              Show this message and exit.

Commands:
  create-customer                 Create a new customer.
  delete-customer                 Delete a customer.
  get-performance-availabilities  Get performance availabilities.
  get-performance-prices          Get performance prices.
```
